# Generated by Django 4.2 on 2023-04-14 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gamekeyservice", "0002_removed_price_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="discount",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2),
        ),
    ]
