# Generated by Django 4.2 on 2023-04-14 11:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gamekeyservice", "0003_discount_edit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="license_number",
        ),
    ]
