# Generated by Django 4.2 on 2023-05-02 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamekeyservice', '0004_customer_modified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='key',
            name='is_active',
        ),
    ]
