# Generated by Django 4.2 on 2023-05-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamekeyservice', '0005_remove_key_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='discount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='price',
            field=models.IntegerField(),
        ),
    ]
