# Generated by Django 4.2 on 2023-05-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamekeyservice', '0008_alter_game_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='discount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
