# Generated by Django 4.2 on 2023-05-09 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamekeyservice', '0010_alter_game_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='release_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
